name: CI pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run scripts/builder.py rectangles_intersection.cpp
        run: python scripts/builder.py rectangles_intersection.cpp

      - name: Run scripts/tester.py rectangles_intersection.cpp
        run: python scripts/tester.py rectangles_intersection.cpp 1

      - name: Run scripts/builder.py line_segments_intersection.cpp
        run: python scripts/builder.py line_segments_intersection.cpp

      - name: Run scripts/tester.py line_segments_intersection.cpp
        run: python scripts/tester.py line_segments_intersection.cpp 1

      - name: Run scripts/builder.py divisible_sequence.cpp
        run: python scripts/builder.py divisible_sequence.cpp

      - name: Run scripts/tester.py divisible_sequence.cpp
        run: python scripts/tester.py divisible_sequence.cpp 15

      - name: Run scripts/builder.py divisible_sequence.c
        run: python scripts/builder.py divisible_sequence.c

      - name: Run scripts/tester.py divisible_sequence.c
        run: python scripts/tester.py divisible_sequence.c 15