name: CI pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run scripts/builder.py rectangles_intersection
        run: python scripts/builder.py rectangles_intersection

      - name: Run scripts/tester.py rectangles_intersection
        run: python scripts/tester.py rectangles_intersection 1

      - name: Run scripts/builder.py line_segments_intersection
        run: python scripts/builder.py line_segments_intersection

      - name: Run scripts/tester.py line_segments_intersection
        run: python scripts/tester.py line_segments_intersection 1
